# Generated by Django 4.1.1 on 2022-10-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cave_core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globals",
            name="limit_personal_sessions",
        ),
        migrations.RemoveField(
            model_name="globals",
            name="limit_team_sessions",
        ),
        migrations.RemoveField(
            model_name="globals",
            name="require_email_validation",
        ),
        migrations.RemoveField(
            model_name="globals",
            name="use_status_acceptance",
        ),
    ]
