# Generated by Django 4.1.1 on 2022-10-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cave_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="This User's current session",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cave_core.sessions",
                verbose_name="session",
            ),
        ),
        migrations.DeleteModel(
            name="UserSessions",
        ),
    ]
