# Generated by Django 4.1.1 on 2022-10-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cave_core", "0002_customuser_session_delete_usersessions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagesections",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("photo_only", "Photo Only"),
                    ("video_only", "Video Only"),
                    ("break", "Break"),
                    ("photo_header", "Photo Header"),
                    ("photo_header_left", "Photo Header Left"),
                    ("photo_header_right", "Photo Header Right"),
                    ("html_content", "HTML Content"),
                    ("photo_quote", "Photo Quote"),
                    ("photo_resource", "Photo Resource"),
                    ("faq", "FAQ"),
                ],
                default="photo_only",
                help_text="The section type to determine the type of section to display",
                max_length=32,
                verbose_name="Section Type",
            ),
        ),
        migrations.DeleteModel(
            name="SectionTypes",
        ),
    ]
